# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "TralahM"
title_separator          : "| "
subtitle                 : "The African Tek Nerd"
name                     : "Tralah M Brian"
description              : "Mathematician and Computer Scientist ,Programmer, Author, Pan-African,Kenyan,Systems Engineer, Researcher, Machine Learning Engineer, NLP , Robotics, UNIX, Linux, VIM, Blockchain, "
url                      : "https://tralahm.tralahtek.com"
baseurl                  : ""
repository               : "TralahM/TralahM.github.io"
teaser                   : "/images/tekblogquote.png"
logo                     : "/images/completelogo.svg"
masthead_title           : "TralahM"
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # "disqus"
  disqus:
    shortname            : # "TralahM"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : "github-dark" # (default)= "github-light"
    issue_term           : "pathname" # (default)
staticman:
  allowedFields          :
    - 'name'
    - 'email'
    - 'url'
    - 'message'
  branch                 : "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : true
  path                   : "/_data/comments/{options.slug}" # (default)
  requiredFields         :
    - 'name'
    - 'email'
    - 'message'
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                : "6LeXjeYZAAAAAI3uIvVpEQu7yr34iXN0WT3AMGAM"
  secret                 : "V3NQ1MJ0fquGuK5suKC3tWXozf2X+O8BDIlgz6zTO6vI/JKx0t5MD2lyZrZD+DfGPxzTFV6a+Mk008Vktn9RbVmtrV/uz9T/KUgCy31Jcx17p0xG7QaZ7a1mY0xpXKZPNMBPXOfcxoDt5VkUaPAVqH9dEF5Cr4cv8pAYuArubOY="
atom_feed:
  path                   : feed.xml # blank (default) uses feed.xml
search                   : true
search_full_content      : true # true, false (default)
search_provider          : google # (default) lunr, algolia
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : "2bd7f4d612e244c74"
  instant_search         : true
# SEO Related
google_site_verification : "WurxhKVwJmUJaZQGvMiHw1prU1ZTDivvleRk5xpCRM0"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : 'TralahM'
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "/images/completelogo.svg"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-137830513-1"


# Site Author
author:
  name             : "Tralah M Brian"
  avatar           : "/images/TralahM.png"
  bio              : "Computer Scientist, Programmer, Writer, African. As our people say, a man who pays respect to the great paves way for his own greatness"
  location         : "Nairobi, Kenya, Africa"
  email            : "musyoki.brian@tralahtek.com"
  links:
    # - label: "Email"
    #   icon: "fas fa-fw fa-envelope-square"
    #   url: mailto:briantralah@tralatek.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tralahm.tralahtek.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TralahM"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TralahM"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/tralahm"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TralahM"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TralahM"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/TralahM"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.com/TralahM"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/tralahm"
      # url:


# Reading Files
include:
  - .htaccess
  - _pages
  - "*.html"
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - ".github/*"
  - PULL_REQUEST_TEMPLATE.md
  - CODE_OF_CONDUCT.md
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:title/ #/:categories/:title/
paginate: 7 # amount of posts to show
paginate_path: /page:num/
timezone: 'Africa/Nairobi'


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
    # _posts
    -
        scope:
            path: ""
            type: posts
        values:
            layout: single
            author_profile: true
            read_time: true
            comments:  false
            share: true
            related: true
            rating: 5
            toc: true
            toc_label: "Contents"

    # _pages
    -
        scope:
            path: ""
            type: pages
        values:
            layout: single
            author_profile: true
            share: true
